#!/usr/bin/env bash
# Generates api/.env from the secrets in .secrets/, creating any that are
# missing. Existing values are never regenerated, so restarting the database
# does not orphan the encrypted rows in it.
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

ENV_FILE="$ROOT/api/.env"

# Key-encryption key, blind-index key and token pepper are all 32 raw bytes.
# Losing DLT_KEK_V1 makes every encrypted column unreadable, by design.
KEK="$(secret kek_v1)"
BIDX="$(secret blind_index_key)"
PEPPER="$(secret token_pepper)"
FLASK_SECRET="$(secret flask_secret_key)"
APP_PASSWORD="$(secret db_app_password)"

if [[ -f "$ENV_FILE" && "${DLT_FORCE_ENV:-0}" != "1" ]]; then
    log "api/.env already exists — leaving it alone (DLT_FORCE_ENV=1 to rewrite)"
    exit 0
fi

# The password is percent-encoded: libpq URIs treat @ : / ? # as delimiters.
ENC_PASSWORD="$(python3 -c 'import sys,urllib.parse;print(urllib.parse.quote(sys.argv[1],safe=""))' "$APP_PASSWORD")"

if [[ "$DB_SSLMODE" == "verify-ca" ]]; then
    SSL_PARAMS="sslmode=verify-ca&sslrootcert=$CERTS/ca.crt"
else
    SSL_PARAMS="sslmode=$DB_SSLMODE"
fi

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by infra/scripts/write-env.sh — do not commit.
# Regenerate the database URL with: make db-up DLT_FORCE_ENV=1

DLT_ENV=development
DLT_SECRET_KEY=$FLASK_SECRET

# --- Database -------------------------------------------------------------
# verify-ca pins the server to the CA in infra/container/certs, so a leaked
# connection string cannot be replayed against an impostor server.
DATABASE_URL='postgresql+psycopg://$DB_APP_USER:$ENC_PASSWORD@127.0.0.1:$DB_HOST_PORT/$DB_NAME?$SSL_PARAMS'

# --- Cryptography ---------------------------------------------------------
# Key-encryption key. Every user row holds a data key wrapped by this. Rotate
# by adding DLT_KEK_V2 and setting DLT_KEK_ACTIVE_VERSION=2; keep V1 so old
# rows stay readable until 'flask crypto rewrap' has run.
DLT_KEK_V1=$KEK
DLT_KEK_ACTIVE_VERSION=1

# Deterministic HMAC key for the email lookup index.
DLT_BLIND_INDEX_KEY=$BIDX

# HMAC key for hashing scan tokens, session tokens and relay tokens at rest.
DLT_TOKEN_PEPPER=$PEPPER

# --- Web ------------------------------------------------------------------
DLT_FRONTEND_ORIGIN=http://localhost:5173
DLT_PUBLIC_BASE_URL=http://localhost:5173
DLT_COOKIE_SECURE=false

# --- Providers ------------------------------------------------------------
# console writes mail to stdout; use smtp in production.
DLT_MAIL_PROVIDER=console
DLT_MAIL_FROM=no-reply@localhost
# DLT_SMTP_HOST=
# DLT_SMTP_PORT=587
# DLT_SMTP_USERNAME=
# DLT_SMTP_PASSWORD=
# DLT_SMTP_STARTTLS=true

# null never resolves a location; header reads a CDN-provided city header.
DLT_GEO_PROVIDER=null
# DLT_GEO_CITY_HEADER=CF-IPCity
# DLT_GEO_REGION_HEADER=CF-Region
# DLT_GEO_COUNTRY_HEADER=CF-IPCountry

# --- Retention ------------------------------------------------------------
DLT_SCAN_RETENTION_DAYS=90
DLT_RELAY_RETENTION_DAYS=30
DLT_AUDIT_RETENTION_DAYS=365
ENV

chmod 0600 "$ENV_FILE"
log "Wrote $ENV_FILE (mode 0600)"
