"""initial schema

Revision ID: fce7a829e1fd
Revises:
Create Date: 2026-09-16 10:44:26.217858
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "fce7a829e1fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email_bidx", sa.LargeBinary(length=32), nullable=False),
        sa.Column("email_enc", sa.LargeBinary(), nullable=False),
        sa.Column("name_enc", sa.LargeBinary(), nullable=True),
        sa.Column("phone_enc", sa.LargeBinary(), nullable=True),
        sa.Column("address_enc", sa.LargeBinary(), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("dek_wrapped", sa.LargeBinary(), nullable=False),
        sa.Column("dek_version", sa.SmallInteger(), nullable=False),
        sa.Column("design_seed", sa.LargeBinary(), nullable=False),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notify_on_scan", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_bidx", name=op.f("uq_users_email_bidx")),
        schema="dlt",
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("subject_user_id", sa.Uuid(), nullable=True),
        sa.Column("tag_id", sa.Uuid(), nullable=True),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["dlt.users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["dlt.users.id"],
            name=op.f("fk_audit_events_subject_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        schema="dlt",
    )
    op.create_index(
        "ix_audit_events_subject_at",
        "audit_events",
        ["subject_user_id", "at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_audit_events_action"), "audit_events", ["action"], unique=False, schema="dlt"
    )
    op.create_index(
        op.f("ix_dlt_audit_events_at"), "audit_events", ["at"], unique=False, schema="dlt"
    )
    op.create_index(
        op.f("ix_dlt_audit_events_expires_at"),
        "audit_events",
        ["expires_at"],
        unique=False,
        schema="dlt",
    )
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('verify_email', 'reset_password')",
            name=op.f("ck_email_tokens_purpose_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dlt.users.id"],
            name=op.f("fk_email_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_tokens_token_hash")),
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_email_tokens_expires_at"),
        "email_tokens",
        ["expires_at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        "ix_email_tokens_user_purpose",
        "email_tokens",
        ["user_id", "purpose"],
        unique=False,
        schema="dlt",
    )
    op.create_table(
        "recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dlt.users.id"],
            name=op.f("fk_recovery_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_codes")),
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_recovery_codes_user_id"),
        "recovery_codes",
        ["user_id"],
        unique=False,
        schema="dlt",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("client_label", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dlt.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_sessions_idle_expires_at"),
        "sessions",
        ["idle_expires_at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="dlt"
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("token_enc", sa.LargeBinary(), nullable=False),
        sa.Column("token_version", sa.SmallInteger(), nullable=False),
        sa.Column("label_enc", sa.LargeBinary(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lost_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("design", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reveal_name", sa.Boolean(), nullable=False),
        sa.Column("reveal_message_relay", sa.Boolean(), nullable=False),
        sa.Column("notify_on_scan", sa.Boolean(), nullable=False),
        sa.Column("scan_count", sa.Integer(), nullable=False),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('safe', 'lost')", name=op.f("ck_tags_status_valid")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["dlt.users.id"], name=op.f("fk_tags_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_tags_token_hash")),
        schema="dlt",
    )
    op.create_index(op.f("ix_dlt_tags_user_id"), "tags", ["user_id"], unique=False, schema="dlt")
    op.create_index(
        "ix_tags_user_created", "tags", ["user_id", "created_at"], unique=False, schema="dlt"
    )
    op.create_table(
        "relay_threads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("finder_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("finder_contact_enc", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["dlt.tags.id"],
            name=op.f("fk_relay_threads_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dlt.users.id"],
            name=op.f("fk_relay_threads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relay_threads")),
        sa.UniqueConstraint("finder_token_hash", name=op.f("uq_relay_threads_finder_token_hash")),
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_relay_threads_expires_at"),
        "relay_threads",
        ["expires_at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_relay_threads_tag_id"), "relay_threads", ["tag_id"], unique=False, schema="dlt"
    )
    op.create_index(
        op.f("ix_dlt_relay_threads_user_id"),
        "relay_threads",
        ["user_id"],
        unique=False,
        schema="dlt",
    )
    op.create_table(
        "scan_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shared_location", sa.Boolean(), nullable=False),
        sa.Column("location_enc", sa.LargeBinary(), nullable=True),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("client_label", sa.String(length=64), nullable=True),
        sa.Column("revealed_contact", sa.Boolean(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["dlt.tags.id"], name=op.f("fk_scan_events_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_events")),
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_scan_events_expires_at"),
        "scan_events",
        ["expires_at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_scan_events_ip_hash"), "scan_events", ["ip_hash"], unique=False, schema="dlt"
    )
    op.create_index(
        op.f("ix_dlt_scan_events_occurred_at"),
        "scan_events",
        ["occurred_at"],
        unique=False,
        schema="dlt",
    )
    op.create_index(
        op.f("ix_dlt_scan_events_tag_id"), "scan_events", ["tag_id"], unique=False, schema="dlt"
    )
    op.create_index(
        "ix_scan_events_tag_occurred",
        "scan_events",
        ["tag_id", "occurred_at"],
        unique=False,
        schema="dlt",
    )
    op.create_table(
        "relay_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("sender", sa.String(length=16), nullable=False),
        sa.Column("body_enc", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sender IN ('finder', 'owner')", name=op.f("ck_relay_messages_sender_valid")
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["dlt.relay_threads.id"],
            name=op.f("fk_relay_messages_thread_id_relay_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relay_messages")),
        schema="dlt",
    )
    op.create_index(
        "ix_relay_messages_thread_created",
        "relay_messages",
        ["thread_id", "created_at"],
        unique=False,
        schema="dlt",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_relay_messages_thread_created", table_name="relay_messages", schema="dlt")
    op.drop_table("relay_messages", schema="dlt")
    op.drop_index("ix_scan_events_tag_occurred", table_name="scan_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_scan_events_tag_id"), table_name="scan_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_scan_events_occurred_at"), table_name="scan_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_scan_events_ip_hash"), table_name="scan_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_scan_events_expires_at"), table_name="scan_events", schema="dlt")
    op.drop_table("scan_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_relay_threads_user_id"), table_name="relay_threads", schema="dlt")
    op.drop_index(op.f("ix_dlt_relay_threads_tag_id"), table_name="relay_threads", schema="dlt")
    op.drop_index(op.f("ix_dlt_relay_threads_expires_at"), table_name="relay_threads", schema="dlt")
    op.drop_table("relay_threads", schema="dlt")
    op.drop_index("ix_tags_user_created", table_name="tags", schema="dlt")
    op.drop_index(op.f("ix_dlt_tags_user_id"), table_name="tags", schema="dlt")
    op.drop_table("tags", schema="dlt")
    op.drop_index(op.f("ix_dlt_sessions_user_id"), table_name="sessions", schema="dlt")
    op.drop_index(op.f("ix_dlt_sessions_idle_expires_at"), table_name="sessions", schema="dlt")
    op.drop_table("sessions", schema="dlt")
    op.drop_index(op.f("ix_dlt_recovery_codes_user_id"), table_name="recovery_codes", schema="dlt")
    op.drop_table("recovery_codes", schema="dlt")
    op.drop_index("ix_email_tokens_user_purpose", table_name="email_tokens", schema="dlt")
    op.drop_index(op.f("ix_dlt_email_tokens_expires_at"), table_name="email_tokens", schema="dlt")
    op.drop_table("email_tokens", schema="dlt")
    op.drop_index(op.f("ix_dlt_audit_events_expires_at"), table_name="audit_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_audit_events_at"), table_name="audit_events", schema="dlt")
    op.drop_index(op.f("ix_dlt_audit_events_action"), table_name="audit_events", schema="dlt")
    op.drop_index("ix_audit_events_subject_at", table_name="audit_events", schema="dlt")
    op.drop_table("audit_events", schema="dlt")
    op.drop_table("users", schema="dlt")
    # ### end Alembic commands ###
